
const app=document.querySelector("#app"),modal=document.querySelector("#modal"),modalContent=document.querySelector("#modalContent"),toast=document.querySelector("#toast");
let session=null,profile=null;

const pages={
 spaces:["Espaces","Les communautés de WHADALZON."],
 discover:["Découvrir","Trouve des membres et des idées dans la ville."],
 events:["Événements","Les activités et rencontres à venir."],
 channels:["Canaux","Les sources publiques que tu veux suivre."],
 messages:["Messages","Discute directement avec les membres."],
 saved:["Enregistrés","Tes contenus importants."],
 notifications:["Notifications","Tes dernières interactions."],
 profile:["Mon profil","Gère ton identité et ton activité."]
};

function toastMsg(t){toast.textContent=t;toast.classList.add("show");clearTimeout(window.tm);window.tm=setTimeout(()=>toast.classList.remove("show"),2500)}
function initials(n="WH"){return n.trim().split(/\s+/).slice(0,2).map(x=>x[0]).join("").toUpperCase()||"WH"}
function esc(s=""){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function ago(d){const m=Math.max(1,Math.floor((Date.now()-new Date(d).getTime())/60000));return m<60?m+" min":m<1440?Math.floor(m/60)+" h":Math.floor(m/1440)+" j"}
function active(p){document.querySelectorAll(".nav,.mobile-nav button").forEach(x=>x.classList.toggle("active",x.dataset.page===p))}
function updateIdentity(){const n=profile?.full_name||profile?.username||session?.user.email.split("@")[0]||"Membre",i=initials(n);["topAvatar","sideAvatar"].forEach(id=>{const x=document.getElementById(id);if(x)x.textContent=i});const a=document.getElementById("sideName"),b=document.getElementById("sideCity");if(a)a.textContent=n;if(b)b.textContent=(profile?.city||"Goma")+" · membre"}
async function loadProfile(){if(!session)return;const r=await db.from("profiles").select("*").eq("id",session.user.id).maybeSingle();if(r.error){console.error(r.error);return}if(!r.data){const p={id:session.user.id,full_name:session.user.user_metadata?.full_name||"",city:"Goma",bio:""};const x=await db.from("profiles").insert(p).select("*").single();profile=x.data||p}else profile=r.data;updateIdentity()}
function authModal(){
 modalContent.innerHTML='<span class="kicker">WHADALZON</span><h2>Bienvenue dans la ville</h2><p>Connecte-toi ou crée ton compte pour participer.</p><div class="auth-tabs"><button class="auth-tab active" data-auth="login">Connexion</button><button class="auth-tab" data-auth="signup">Créer un compte</button></div><div id="authForm"></div>';
 modal.classList.add("open");let mode="login";
 const render=()=>{document.querySelectorAll(".auth-tab").forEach(x=>x.classList.toggle("active",x.dataset.auth===mode));document.querySelector("#authForm").innerHTML=(mode==="signup"?'<input class="field" id="authName" placeholder="Nom complet">':"")+'<input class="field" id="authEmail" type="email" placeholder="Adresse e-mail"><input class="field" id="authPassword" type="password" placeholder="Mot de passe"><button class="submit" id="authSubmit">'+(mode==="login"?"Se connecter":"Créer mon compte")+"</button>";
 document.querySelector("#authSubmit").onclick=async()=>{const email=document.querySelector("#authEmail").value.trim(),password=document.querySelector("#authPassword").value,name=document.querySelector("#authName")?.value.trim()||"";if(!email||password.length<6){toastMsg("E-mail et mot de passe : 6 caractères minimum.");return}const r=mode==="login"?await db.auth.signInWithPassword({email,password}):await db.auth.signUp({email,password,options:{data:{full_name:name}}});if(r.error){toastMsg(r.error.message);return}if(mode==="signup"&&!r.data.session){toastMsg("Compte créé. Vérifie ton e-mail.");modal.classList.remove("open");return}session=r.data.session;await loadProfile();modal.classList.remove("open");home()}};
 document.querySelectorAll(".auth-tab").forEach(x=>x.onclick=()=>{mode=x.dataset.auth;render()});render();
}
function requireAuth(){if(!session){authModal();return false}return true}

async function getPosts(userId=""){let q=db.from("posts").select("id,content,image_url,location,created_at,user_id,profiles(id,username,full_name,avatar_url,city)").order("created_at",{ascending:false}).limit(50);if(userId)q=q.eq("user_id",userId);const r=await q;if(r.error){console.error(r.error);return []}return r.data||[]}
function postCard(p){
 const u=p.profiles||{},n=u.full_name||u.username||"Membre";
 return '<article class="post card"><div class="post-head"><span class="avatar">'+initials(n)+'</span><div><strong>'+esc(n)+'</strong><small>'+esc(u.city||p.location||"Goma")+" · "+ago(p.created_at)+'</small></div>'+(session&&p.user_id===session.user.id?'<button class="icon-btn" data-action="delete-post" data-post="'+p.id+'"><i class="fa-solid fa-trash"></i></button>':"")+'</div><p>'+esc(p.content)+'</p>'+(p.image_url?'<img class="post-image" src="'+esc(p.image_url)+'" alt="Publication">':"")+'<div class="post-actions"><button data-action="like" data-post="'+p.id+'"><i class="fa-regular fa-heart"></i> J’aime</button><button data-action="comment" data-post="'+p.id+'"><i class="fa-regular fa-comment"></i> Commenter</button><button data-action="share"><i class="fa-solid fa-share-nodes"></i> Partager</button></div></article>'
}
async function home(){
 active("home");app.innerHTML='<div class="loading card">Chargement de ta ville…</div>';const posts=await getPosts();
 app.innerHTML='<section class="hero"><div><span class="kicker">WHADALZON · GOMA</span><h1>La ville numérique qui nous connecte.</h1><p>Communautés, événements, discussions et projets réunis dans une seule expérience.</p><div class="actions"><button class="primary" data-page="spaces"><i class="fa-solid fa-layer-group"></i> Explorer les espaces</button><button class="secondary" data-page="create"><i class="fa-solid fa-plus"></i> Créer</button></div></div></section><div class="section-head"><div><span class="kicker">TON QUARTIER NUMÉRIQUE</span><h2>Qu’est-ce qui se passe ?</h2></div></div><div class="features"><button class="feature card" data-page="spaces"><i class="fa-solid fa-layer-group"></i><strong>Espaces</strong><small>Crée ou rejoins des communautés.</small></button><button class="feature card" data-page="events"><i class="fa-regular fa-calendar"></i><strong>Événements</strong><small>Les activités de la ville.</small></button><button class="feature card" data-page="discover"><i class="fa-solid fa-compass"></i><strong>Découvrir</strong><small>Des membres et des idées.</small></button></div><section class="composer card"><div class="compose-row"><span class="avatar">'+initials(profile?.full_name||"SM")+'</span><button class="compose-button" data-page="create">Partager une idée avec la ville...</button></div><div class="tools"><button data-page="create"><i class="fa-regular fa-image"></i>Photo</button><button data-page="create"><i class="fa-regular fa-lightbulb"></i>Idée</button><button data-page="events"><i class="fa-regular fa-calendar-plus"></i>Événement</button></div></section>'+(posts.length?posts.map(postCard).join(""):'<article class="post card"><div class="city-card"><span class="city-icon"><i class="fa-solid fa-city"></i></span><div><strong>GOMA</strong><small>Aucune publication. Sois le premier à partager.</small></div></div></article>')
}
async function create(){
 if(!requireAuth())return;
 modalContent.innerHTML='<span class="kicker">CRÉER</span><h2>Partager avec la ville</h2><p>Publie une idée, une annonce ou une actualité.</p><textarea class="field" id="postContent" rows="6" placeholder="Qu’est-ce que tu veux partager ?"></textarea><input class="field" id="postLocation" placeholder="Lieu (facultatif)" value="Goma"><button class="submit" id="publish"><i class="fa-solid fa-paper-plane"></i> Publier</button>';modal.classList.add("open");
 document.querySelector("#publish").onclick=async()=>{const content=document.querySelector("#postContent").value.trim(),location=document.querySelector("#postLocation").value.trim();if(!content)return toastMsg("Écris d’abord ta publication.");const r=await db.from("posts").insert({user_id:session.user.id,content,location:location||null});if(r.error)return toastMsg(r.error.message);modal.classList.remove("open");toastMsg("Publication publiée.");home()}
}
async function likePost(id){if(!requireAuth())return;const q=await db.from("likes").select("id").eq("post_id",id).eq("user_id",session.user.id).maybeSingle();if(q.data){await db.from("likes").delete().eq("id",q.data.id);toastMsg("J’aime retiré")}else{const r=await db.from("likes").insert({post_id:id,user_id:session.user.id});toastMsg(r.error?r.error.message:"J’aime ajouté")}}
async function comments(id){
 const r=await db.from("comments").select("id,content,created_at,profiles(full_name,username)").eq("post_id",id).order("created_at",{ascending:true});if(r.error)return toastMsg(r.error.message);
 modalContent.innerHTML='<span class="kicker">DISCUSSION</span><h2>Commentaires</h2><div class="comments-list">'+((r.data||[]).map(c=>'<div class="comment"><b>'+esc(c.profiles?.full_name||c.profiles?.username||"Membre")+'</b><p>'+esc(c.content)+'</p><small>'+ago(c.created_at)+'</small></div>').join("")||"<p>Aucun commentaire.</p>")+'</div>'+(session?'<textarea class="field" id="commentText" rows="3" placeholder="Écrire un commentaire…"></textarea><button class="submit" id="commentSend">Commenter</button>':"");modal.classList.add("open");
 if(session)document.querySelector("#commentSend").onclick=async()=>{const content=document.querySelector("#commentText").value.trim();if(!content)return;const x=await db.from("comments").insert({post_id:id,user_id:session.user.id,content});if(x.error)return toastMsg(x.error.message);comments(id)}
}
async function discover(){
 active("discover");app.innerHTML='<div class="loading card">Recherche des membres…</div>';const r=await db.from("profiles").select("id,username,full_name,city,bio").neq("id",session?.user.id||"00000000-0000-0000-0000-000000000000").limit(30);if(r.error)return toastMsg(r.error.message);
 app.innerHTML='<section class="page"><div class="page-head card"><span class="kicker">DÉCOUVRIR</span><h1>Les membres de la ville</h1><p>Découvre les personnes présentes sur WHADALZON.</p></div><div class="people-grid">'+((r.data||[]).map(u=>'<article class="person card"><span class="avatar">'+initials(u.full_name||u.username||"M")+'</span><strong>'+esc(u.full_name||u.username||"Membre")+'</strong><small>'+esc(u.city||"Goma")+'</small><p>'+esc(u.bio||"Membre de WHADALZON.")+'</p><button data-action="view-profile" data-user="'+u.id+'">Voir le profil</button><button data-action="message-user" data-user="'+u.id+'">Message</button></article>').join("")||"<p>Aucun autre membre.</p>")+'</div></section>'
}
async function viewProfile(id){
 const r=await db.from("profiles").select("*").eq("id",id).single();if(r.error)return toastMsg("Profil introuvable.");const u=r.data,posts=await getPosts(id);const f=session?await db.from("follows").select("id").eq("follower_id",session.user.id).eq("following_id",id).maybeSingle():{data:null};active("discover");
 app.innerHTML='<section class="page"><div class="profile-cover card"><span class="avatar avatar-large">'+initials(u.full_name||u.username||"M")+'</span><div><span class="kicker">PROFIL</span><h1>'+esc(u.full_name||u.username||"Membre")+'</h1><p>'+esc(u.city||"Goma")+" · "+esc(u.bio||"")+'</p></div>'+(session&&id!==session.user.id?'<button class="primary follow-btn" data-action="follow" data-user="'+id+'">'+(f.data?"Ne plus suivre":"Suivre")+'</button>':"")+'</div>'+(posts.length?posts.map(postCard).join(""):'<div class="tile card">Aucune publication.</div>')+'</section>'
}
async function followUser(id){if(!requireAuth())return;const q=await db.from("follows").select("id").eq("follower_id",session.user.id).eq("following_id",id).maybeSingle();if(q.data)await db.from("follows").delete().eq("id",q.data.id);else await db.from("follows").insert({follower_id:session.user.id,following_id:id});viewProfile(id)}
async function profilePage(){
 if(!requireAuth())return;active("profile");const posts=await getPosts(session.user.id);
 app.innerHTML='<section class="page"><div class="profile-cover card"><span class="avatar avatar-large">'+initials(profile?.full_name||"M")+'</span><div><span class="kicker">MON PROFIL</span><h1>'+esc(profile?.full_name||profile?.username||"Membre")+'</h1><p>'+esc(profile?.city||"Goma")+" · "+esc(session.user.email)+'</p></div></div><div class="card profile-edit"><h3>Modifier mon profil</h3><input class="field" id="editName" value="'+esc(profile?.full_name||"")+'" placeholder="Nom complet"><input class="field" id="editUsername" value="'+esc(profile?.username||"")+'" placeholder="Nom d’utilisateur"><input class="field" id="editCity" value="'+esc(profile?.city||"Goma")+'" placeholder="Ville"><textarea class="field" id="editBio" rows="3" placeholder="Bio">'+esc(profile?.bio||"")+'</textarea><button class="submit" id="saveProfile">Enregistrer</button><button class="danger-btn" id="logout">Se déconnecter</button></div>'+posts.map(postCard).join("")+'</section>';
 document.querySelector("#saveProfile").onclick=async()=>{const r=await db.from("profiles").update({full_name:document.querySelector("#editName").value.trim(),username:document.querySelector("#editUsername").value.trim()||null,city:document.querySelector("#editCity").value.trim()||"Goma",bio:document.querySelector("#editBio").value.trim()}).eq("id",session.user.id);if(r.error)return toastMsg(r.error.message);await loadProfile();toastMsg("Profil mis à jour");profilePage()};
 document.querySelector("#logout").onclick=()=>db.auth.signOut();
}
async function notifications(){if(!requireAuth())return;active("notifications");const r=await db.from("notifications").select("id,type,is_read,created_at,profiles(full_name,username)").eq("user_id",session.user.id).order("created_at",{ascending:false}).limit(50);app.innerHTML='<section class="page"><div class="page-head card"><span class="kicker">NOTIFICATIONS</span><h1>Activité</h1><p>'+((r.data||[]).length)+' notification(s).</p></div><div class="card list-box">'+((r.data||[]).map(n=>'<div class="list-row"><i class="fa-regular fa-bell"></i><div><strong>'+esc(n.profiles?.full_name||"WHADALZON")+'</strong><small>'+esc(n.type)+" · "+ago(n.created_at)+'</small></div></div>').join("")||"<p>Aucune notification.</p>")+'</div></section>'}
async function startChat(id){if(!requireAuth()||id===session.user.id)return;const mine=await db.from("conversation_members").select("conversation_id").eq("user_id",session.user.id);if(mine.error)return toastMsg(mine.error.message);for(const row of (mine.data||[])){const other=await db.from("conversation_members").select("user_id").eq("conversation_id",row.conversation_id).eq("user_id",id).maybeSingle();if(other.data)return chat(row.conversation_id)}const c=await db.from("conversations").insert({}).select("id").single();if(c.error)return toastMsg(c.error.message);const m=await db.from("conversation_members").insert([{conversation_id:c.data.id,user_id:session.user.id},{conversation_id:c.data.id,user_id:id}]);if(m.error)return toastMsg(m.error.message);chat(c.data.id)}
async function chat(id){const access=await db.from("conversation_members").select("user_id").eq("conversation_id",id).eq("user_id",session.user.id).maybeSingle();if(!access.data)return toastMsg("Conversation inaccessible.");const r=await db.from("messages").select("id,content,created_at,sender_id,profiles(full_name,username)").eq("conversation_id",id).order("created_at",{ascending:true});modalContent.innerHTML='<span class="kicker">MESSAGE</span><h2>Conversation</h2><div class="chat-box">'+((r.data||[]).map(m=>'<div class="bubble '+(m.sender_id===session.user.id?"mine":"")+'"><b>'+esc(m.profiles?.full_name||m.profiles?.username||"Membre")+'</b><p>'+esc(m.content)+'</p><small>'+ago(m.created_at)+'</small></div>').join("")||"<p>Commence la conversation.</p>")+'</div><textarea class="field" id="msgText" rows="2" placeholder="Écrire un message…"></textarea><button class="submit" id="sendMsg">Envoyer</button>';modal.classList.add("open");if(window.chatChannel)db.removeChannel(window.chatChannel);window.chatChannel=db.channel("chat-"+id).on("postgres_changes",{event:"INSERT",schema:"public",table:"messages",filter:"conversation_id=eq."+id},()=>chat(id)).subscribe();document.querySelector("#sendMsg").onclick=async()=>{const content=document.querySelector("#msgText").value.trim();if(!content)return;const x=await db.from("messages").insert({conversation_id:id,sender_id:session.user.id,content});if(x.error)return toastMsg(x.error.message);toastMsg("Message envoyé.");chat(id)}}
async function messages(){if(!requireAuth())return;active("messages");const r=await db.from("conversation_members").select("conversation_id").eq("user_id",session.user.id);const ids=(r.data||[]).map(x=>x.conversation_id);if(!ids.length){app.innerHTML='<section class="page"><div class="page-head card"><span class="kicker">MESSAGES</span><h1>Ta messagerie</h1><p>Aucune conversation pour le moment.</p></div><div class="tile card">Va dans <b>Découvrir</b> pour écrire à un membre.</div></section>';return}const o=await db.from("conversation_members").select("conversation_id,user_id,profiles(full_name,username,city)").in("conversation_id",ids).neq("user_id",session.user.id);const map={};(o.data||[]).forEach(x=>map[x.conversation_id]=x.profiles);app.innerHTML='<section class="page"><div class="page-head card"><span class="kicker">MESSAGES</span><h1>Ta messagerie</h1></div><div class="card list-box">'+Object.keys(map).map(id=>'<button class="conversation-row" data-action="open-chat" data-conversation="'+id+'"><span class="avatar">'+initials(map[id]?.full_name||map[id]?.username||"M")+'</span><div><strong>'+esc(map[id]?.full_name||map[id]?.username||"Conversation")+'</strong><small>'+esc(map[id]?.city||"Goma")+'</small></div><i class="fa-solid fa-chevron-right"></i></button>').join("")+'</div></section>'}
function simple(p){active(p);const v=pages[p];if(p==="discover")return discover();if(p==="messages")return messages();if(p==="notifications")return notifications();app.innerHTML='<section class="page"><div class="page-head card"><span class="kicker">WHADALZON</span><h1>'+v[0]+'</h1><p>'+v[1]+'</p></div><div class="grid"><div class="tile card"><i class="fa-solid fa-users"></i><strong>Communautés</strong><small>Cette section est prête pour les prochaines données de la ville.</small></div><div class="tile card"><i class="fa-solid fa-bolt"></i><strong>Supabase connecté</strong><small>Les comptes, profils, publications et interactions sont réels.</small></div></div></section>'}
function go(p){if(p==="home")home();else if(p==="create")create();else if(p==="profile")profilePage();else if(pages[p])simple(p);else home()}

document.addEventListener("click",async e=>{const b=e.target.closest("[data-page]");if(b){e.preventDefault();go(b.dataset.page);return}const a=e.target.closest("[data-action]");if(!a)return;const x=a.dataset.action;if(x==="like")likePost(a.dataset.post);else if(x==="comment")comments(a.dataset.post);else if(x==="view-profile")viewProfile(a.dataset.user);else if(x==="follow")followUser(a.dataset.user);else if(x==="message-user")startChat(a.dataset.user);else if(x==="open-chat")chat(a.dataset.conversation);else if(x==="delete-post"&&confirm("Supprimer cette publication ?")){await db.from("posts").delete().eq("id",a.dataset.post).eq("user_id",session.user.id);home()}else if(x==="share"){try{await navigator.clipboard.writeText(location.href);toastMsg("Lien copié")}catch{toastMsg("Lien prêt à partager")}}});
document.querySelector("#close").onclick=()=>modal.classList.remove("open");modal.addEventListener("click",e=>{if(e.target===modal)modal.classList.remove("open")});
document.querySelector("#search").addEventListener("keydown",async e=>{if(e.key!=="Enter"||!e.target.value.trim())return;const q=e.target.value.trim(),r=await db.from("profiles").select("id,username,full_name,city,bio").or("full_name.ilike.%"+q+"%,username.ilike.%"+q+"%").limit(30);active("discover");app.innerHTML='<section class="page"><div class="page-head card"><span class="kicker">RECHERCHE</span><h1>Résultats pour « '+esc(q)+' »</h1></div><div class="people-grid">'+((r.data||[]).map(u=>'<article class="person card"><span class="avatar">'+initials(u.full_name||u.username||"M")+'</span><strong>'+esc(u.full_name||u.username||"Membre")+'</strong><small>'+esc(u.city||"Goma")+'</small><button data-action="view-profile" data-user="'+u.id+'">Voir le profil</button><button data-action="message-user" data-user="'+u.id+'">Message</button></article>').join("")||"<p>Aucun résultat.</p>")+'</div></section>'});

async function boot(){const r=await db.auth.getSession();session=r.data.session;if(session)await loadProfile();updateIdentity();if(session)home();else authModal();db.auth.onAuthStateChange(async(_,s)=>{session=s;if(session)await loadProfile();else{profile=null;updateIdentity();authModal()}})}
boot();if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js").catch(()=>{}));
