const app=document.querySelector("#app"),modal=document.querySelector("#modal"),modalContent=document.querySelector("#modalContent"),toast=document.querySelector("#toast");
const pages={spaces:["Espaces","Des communautés pour les écoles, quartiers, associations, projets et passions."],discover:["Découvrir","Explore les communautés et contenus qui peuvent t’intéresser."],events:["Événements","Découvre les rencontres et activités publiées dans la ville."],channels:["Canaux","Suis les sources publiques que tu veux retrouver facilement."],messages:["Messages","Une messagerie privée et des groupes intégrés à WHADALZON."],saved:["Enregistrés","Retrouve les contenus que tu souhaites garder."],notifications:["Notifications","Toutes les nouvelles activités et interactions."],profile:["Mon profil","Ton identité, tes espaces et ton activité."]};
function showToast(t){toast.textContent=t;toast.classList.add("show");clearTimeout(window.tt);window.tt=setTimeout(()=>toast.classList.remove("show"),2200)}
function active(p){document.querySelectorAll("[data-page]").forEach(x=>x.classList.toggle("active",x.dataset.page===p&&x.classList.contains("nav")||x.dataset.page===p&&x.closest(".mobile-nav")))}
function home(){active("home");app.innerHTML=`<section class="hero"><div><span class="kicker">WHADALZON · GOMA</span><h1>La ville numérique qui nous connecte.</h1><p>Espaces, événements, canaux, discussions et projets réunis dans une seule expérience.</p><div class="actions"><button class="primary" data-page="spaces"><i class="fa-solid fa-layer-group"></i> Explorer les espaces</button><button class="secondary" data-page="create"><i class="fa-solid fa-plus"></i> Créer</button></div></div></section><div class="section-head"><div><span class="kicker">TON QUARTIER NUMÉRIQUE</span><h2>Qu'est-ce qui se passe ?</h2></div></div><div class="features"><button class="feature card" data-page="spaces"><i class="fa-solid fa-layer-group"></i><strong>Espaces</strong><small>Crée ou rejoins des communautés.</small></button><button class="feature card" data-page="events"><i class="fa-regular fa-calendar"></i><strong>Événements</strong><small>Les activités de ta ville.</small></button><button class="feature card" data-page="channels"><i class="fa-solid fa-bullhorn"></i><strong>Canaux</strong><small>Les informations que tu suis.</small></button></div><section class="composer card"><div class="compose-row"><span class="avatar">SM</span><button class="compose-button" data-page="create">Partager une idée avec la ville...</button></div><div class="tools"><button data-page="create"><i class="fa-regular fa-image"></i>Photo</button><button data-page="create"><i class="fa-regular fa-lightbulb"></i>Idée</button><button data-page="create"><i class="fa-regular fa-calendar-plus"></i>Événement</button></div></section><article class="post card"><div class="post-head"><span class="avatar">W</span><div><strong>WHADALZON</strong><small>Annonce · aujourd'hui</small></div><i class="fa-solid fa-ellipsis"></i></div><h3>Bienvenue dans la ville numérique.</h3><p>WHADALZON rassemble les personnes, les communautés et les activités de Goma dans une expérience unique.</p><div class="city-card"><span class="city-icon"><i class="fa-solid fa-city"></i></span><div><strong>GOMA</strong><small>Espaces · Événements · Canaux · Discussions</small></div><i class="fa-solid fa-arrow-right"></i></div><div class="post-actions"><button data-action="like"><i class="fa-regular fa-heart"></i> J'aime</button><button data-action="comment"><i class="fa-regular fa-comment"></i> Commenter</button><button data-action="share"><i class="fa-solid fa-share-nodes"></i> Partager</button></div></article>`;}
function simple(p){active(p);const v=pages[p];app.innerHTML=`<section class="page"><div class="page-head card"><span class="kicker">WHADALZON</span><h1>${v[0]}</h1><p>${v[1]}</p></div><div class="grid"><div class="tile card"><i class="fa-solid fa-users"></i><strong>Communautés</strong><small>Des espaces construits autour des personnes et projets.</small><button data-action="soon">Bientôt</button></div><div class="tile card"><i class="fa-solid fa-bolt"></i><strong>Activité</strong><small>Cette partie sera alimentée par Supabase.</small><button data-action="soon">Bientôt</button></div></div></section>`;}
function create(){modalContent.innerHTML=`<span class="kicker">CRÉER</span><h2>Partager avec la ville</h2><p>Prépare une publication, une idée ou une annonce.</p><input class="field" placeholder="Titre"><textarea class="field" rows="5" placeholder="Écris ton contenu..."></textarea><button class="submit" id="publish">Publier</button>`;modal.classList.add("open");document.querySelector("#publish").onclick=()=>{modal.classList.remove("open");showToast("Publication prête pour Supabase.")};}
function go(p){if(p==="home")home();else if(p==="create")create();else if(pages[p])simple(p);else home();}
document.addEventListener("click",e=>{const b=e.target.closest("[data-page]");if(b){e.preventDefault();go(b.dataset.page)}const a=e.target.closest("[data-action]");if(a)showToast(a.dataset.action==="like"?"J’aime ajouté.":a.dataset.action==="comment"?"Commentaires bientôt disponibles.":"Cette fonction sera connectée à Supabase.");});
document.querySelector("#close").onclick=()=>modal.classList.remove("open");modal.addEventListener("click",e=>{if(e.target===modal)modal.classList.remove("open")});
document.querySelector("#search").addEventListener("keydown",e=>{if(e.key==="Enter"&&e.target.value.trim())showToast("Recherche : "+e.target.value.trim())});
home();
if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js").catch(()=>{}));